// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoxMind.Core.Database;

#nullable disable

namespace VoxMind.Core.Migrations
{
    [DbContext(typeof(VoxMindDbContext))]
    partial class VoxMindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VoxMind.Core.Database.ListeningSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_sessions_started");

                    b.ToTable("ListeningSessions");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SessionSegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<double>("EndTime")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpeakerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_segments_session");

                    b.ToTable("SessionSegments");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SessionSummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionItemsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullTranscript")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyMomentsJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("SessionSummaries");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SpeakerEmbeddingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AudioDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("InitialConfidence")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("idx_embeddings_profile");

                    b.ToTable("SpeakerEmbeddings");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SpeakerProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_profiles_lastseen");

                    b.ToTable("SpeakerProfiles");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SessionSegmentEntity", b =>
                {
                    b.HasOne("VoxMind.Core.Database.ListeningSessionEntity", "Session")
                        .WithMany("Segments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SessionSummaryEntity", b =>
                {
                    b.HasOne("VoxMind.Core.Database.ListeningSessionEntity", "Session")
                        .WithOne("Summary")
                        .HasForeignKey("VoxMind.Core.Database.SessionSummaryEntity", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SpeakerEmbeddingEntity", b =>
                {
                    b.HasOne("VoxMind.Core.Database.SpeakerProfileEntity", "Profile")
                        .WithMany("Embeddings")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("VoxMind.Core.Database.ListeningSessionEntity", b =>
                {
                    b.Navigation("Segments");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("VoxMind.Core.Database.SpeakerProfileEntity", b =>
                {
                    b.Navigation("Embeddings");
                });
#pragma warning restore 612, 618
        }
    }
}
